# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6b2ed12fbe1df8d48423038fd88be2b8aa2c70fc9f84686a3f5934475b4d3a2a1a16242b6050d8e071f92a9b4ae6b5a824a81813fb7627e55d215994d522aa7

test:
  secret_key_base: 2e54943aab2fbebc00df9dc76ee40576ad95ecf214f1105cbaf2cd220e19b8ddfd96cef57dca97ee10041ceb8842ee239c963709e8c9290dd176b707909934e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
